// <auto-generated />
namespace DiabetesTrackerASPAplikacija.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nova3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nova3));
        
        string IMigrationMetadata.Id
        {
            get { return "201806061946135_nova3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
